#!/usr/bin/env node
/* Self-hosted, glyph-subset web fonts for the page (all four faces are SIL Open Font License).

   Fontsource ships each Japanese face as ~120 unicode-range chunks: a page that uses 200 kanji pulls
   ~35 chunks (≈40 KB each) per weight, behind ~720 KB of @font-face CSS. This page's copy is fixed, so
   instead we subset each face to exactly the glyphs the page uses:

     node tools/fonts.mjs          scan the copy, fetch subset woff2s (Google Fonts `text=` API),
                                   write src/fonts/*.woff2 + src/fonts/manifest.json + src/styles/fonts.css
     node tools/fonts.mjs --check  offline: fail if the copy uses a glyph the subsets don't cover
                                   (runs before every `npm run build`)

   Each face gets two files: Latin (full printable Latin, so any Latin text renders) and Japanese
   (only the glyphs in the copy). Scanned: index.html and every .html/.js/.css/.svg under src/. */
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS = join(root, 'src/fonts');
const CSS = join(root, 'src/styles/fonts.css');
const MANIFEST = join(FONTS, 'manifest.json');
const FACES = [
  { family: 'Shippori Mincho', slug: 'shippori-mincho', weights: [400, 700] },
  { family: 'Zen Kaku Gothic New', slug: 'zen-kaku-gothic-new', weights: [400, 500, 700] },
  { family: 'DotGothic16', slug: 'dotgothic16', weights: [400] },
  { family: 'Dela Gothic One', slug: 'dela-gothic-one', weights: [400] },
];
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

// Latin coverage: printable ASCII, Latin-1, Latin Extended-A (ō ū ā…), common punctuation and arrows.
const LATIN = [];
for (const [a, b] of [[0x20, 0x7e], [0xa0, 0xff], [0x100, 0x17f], [0x2010, 0x2027], [0x2030, 0x203a],
                      [0x2190, 0x2193], [0x20ac, 0x20ac], [0x2122, 0x2122], [0x2212, 0x2212]]) {
  for (let c = a; c <= b; c++) LATIN.push(c);
}

function scan() {
  const walk = (dir) => readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) return f === 'fonts' ? [] : walk(p);
    return /\.(html|js|mjs|css|svg)$/.test(f) && p !== CSS ? [p] : [];
  });
  const text = [join(root, 'index.html'), ...walk(join(root, 'src'))].map((f) => readFileSync(f, 'utf8')).join('');
  const cps = new Set();
  for (const ch of text) {
    const cp = ch.codePointAt(0);
    // Japanese scripts and full-width forms, CJK punctuation; everything Latin is covered wholesale.
    if ((cp >= 0x3000 && cp <= 0x30ff) || (cp >= 0x3400 && cp <= 0x9fff) || (cp >= 0xf900 && cp <= 0xfaff) ||
        (cp >= 0xff00 && cp <= 0xffef) || (cp >= 0x2e80 && cp <= 0x2fdf)) cps.add(cp);
  }
  return [...cps].sort((a, b) => a - b);
}

const range = (cps) => {
  const out = [];
  for (let i = 0; i < cps.length; i++) {
    let j = i;
    while (j + 1 < cps.length && cps[j + 1] === cps[j] + 1) j++;
    out.push('U+' + cps[i].toString(16) + (j > i ? '-' + cps[j].toString(16) : ''));
    i = j;
  }
  return out.join(',');
};

if (process.argv.includes('--check')) {
  if (!existsSync(MANIFEST)) { console.error('fonts: no manifest — run `node tools/fonts.mjs` once (needs network)'); process.exit(1); }
  const have = new Set(JSON.parse(readFileSync(MANIFEST, 'utf8')).japanese);
  const missing = scan().filter((cp) => !have.has(cp));
  if (missing.length) {
    console.error(`fonts: ${missing.length} glyph(s) in the copy are not in the subset: ${String.fromCodePoint(...missing)}\n` +
                  '       run `node tools/fonts.mjs` (needs network) to refresh src/fonts/.');
    process.exit(1);
  }
  console.log(`fonts: subset covers all ${have.size} Japanese glyphs in the copy`);
  process.exit(0);
}

async function fetchSubset(family, weight, cps) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weight}` +
              `&text=${encodeURIComponent(String.fromCodePoint(...cps))}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  const src = css.match(/src:\s*url\(([^)]+)\)\s*format\('woff2'\)/)?.[1];
  if (!src) throw new Error(`no woff2 in response for ${family} ${weight}:\n${css.slice(0, 300)}`);
  return Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
}

const ja = scan();
mkdirSync(FONTS, { recursive: true });
let css = `/* Generated by tools/fonts.mjs — do not edit. Glyph subsets of SIL OFL faces:
   Shippori Mincho, Zen Kaku Gothic New, DotGothic16, Dela Gothic One (licences: see /fonts/OFL.txt). */\n`;
let bytes = 0;
for (const { family, slug, weights } of FACES) {
  for (const w of weights) {
    for (const [part, cps] of [['latin', LATIN], ['ja', ja]]) {
      if (!cps.length) continue;
      const buf = await fetchSubset(family, w, cps);
      const file = `${slug}-${w}-${part}.woff2`;
      writeFileSync(join(FONTS, file), buf);
      bytes += buf.length;
      css += `@font-face { font-family: '${family}'; font-style: normal; font-weight: ${w}; font-display: swap;\n` +
             `  src: url(../fonts/${file}) format('woff2'); unicode-range: ${range(cps)}; }\n`;
      console.log(`  ${file.padEnd(36)} ${(buf.length / 1024).toFixed(1).padStart(7)} KB`);
    }
  }
}
writeFileSync(CSS, css);
writeFileSync(MANIFEST, JSON.stringify({ generated: 'tools/fonts.mjs', japanese: ja }, null, 0));
console.log(`fonts: ${ja.length} Japanese glyphs + Latin; ${(bytes / 1024).toFixed(0)} KB of woff2 across all faces; ${(css.length / 1024).toFixed(1)} KB CSS`);
